services:
 client:
   build:
     context: ./client
   container_name: client
   restart: always
   ports:
     - 3000:3000
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost:3001/api
   networks:
     - network

 api:
  build:
    context: ./api
  container_name: api
  rpc_address: cassandra
  restart: always
  ports: 
    - 3001:3001
  environment:
    - CONNECTION_STRING={{ secrets.API_CONNECTION_STRING }}
    - CASSANDRA_KEYSPACE={{ secrets.KEYSPACE }}
    - CASSANDRA_USER={{ secrets.CASSANDRA_USER }}
    - CASSANDRA_PASSWORD={{ secrets.CASSANDRA_PASSWORD }}
  networks:
    - network

 cassandra:
  build:
    context: ./database
  image: cassandra:5.0
  container_name: cassandra
  ports:
    - 3002:3002
    - 9042:9042
    - 9160:9160
  environment:
    - CASSANDRA_USER={{ secrets.CASSANDRA_USER }}
    - CASSANDRA_PASSWORD={{ secrets.CASSANDRA_PASSWORD }}
  volumes:
  - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
   
networks:
 network: